[package]
name = "sound_player"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
env_logger = "0.11.8"
log = "0.4.28"
rodio = "0.21.1"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.16"
tungstenite = "0.27.0"
